#
name: Create astro feature deployment
run-name: Create astro feature deployment
on:
  workflow_dispatch:

jobs:
  check_conditions:
    name: Check conditions
    runs-on: ubuntu-latest
    env:
      REPO_NAME: 'ci-cd' # 'astro-dev-insights-core-ae'
    outputs:
      should-run-next: ${{ steps.condition-check.outputs.run-next }}
    steps:
      - name: Set CURRENT_REPO_NAME
        run: echo "CURRENT_REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Common information
        run: |
          echo "Create astro deployment for the PR ${{ github.event.pull_request.html_url }}"
          echo "Current repo name: ${{env.CURRENT_REPO_NAME}}"
          echo "Core repo name: ${{env.REPO_NAME}}"
          echo "The source branch: ${{github.ref}}"

      - name: Conditions are not met
        run: |
          echo "The deploment can be created only from the non-dev and non-main brunch and can be invocated only from the repo ${{env.REPO_NAME}}"
          echo "Current repo name ${{env.CURRENT_REPO_NAME}} or branch ${{github.ref}} does not satisfy the condition"
        if: env.CURRENT_REPO_NAME != env.REPO_NAME || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

      - id: condition-check
        name: Conditions are met
        run: |
          echo "run-next=true" >> "$GITHUB_OUTPUT"
        if: env.CURRENT_REPO_NAME == env.REPO_NAME && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev'

  create_deployment:
    name: Create astro deployment for the PR
    needs: check_conditions
    if: needs.check_conditions.outputs.should-run-next == 'true'
    runs-on: ubuntu-latest
    env:
      VAR_DATABRIKS_CONN: ${{ secrets.ASTRO_DATABRIKS_CONN }}
      CONFIGIRATION_NAME: "insights-core-ae-${{github.ref}}-dev"
      CONFIGIRATION_DESCRIPTION: "Auto create from the branch ${{github.ref}}"
      CONFIGIRATION_CLUSTER_NAME: "dedicated-cluster"
      CONFIGIRATION_WORKSPACE_NAME: "dev-workspace-insights"
      SCHEDULES_HIBERNATE_AT:
      SCHEDULES_WAKE_AT:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace Parameters in YAML
        run: |
          sed -i -e 's/[[VAR_DATABRIKS_CONN]]/${{env.VAR_DATABRIKS_CONN}}/g' |
          -e 's/[[CONFIGIRATION_NAME]]/${{env.CONFIGIRATION_NAME}}/g' |
          -e 's/[[CONFIGIRATION_DESCRIPTION]]/${{env.CONFIGIRATION_DESCRIPTION}}/g' |
          -e 's/[[CONFIGIRATION_CLUSTER_NAME]]/${{env.CONFIGIRATION_CLUSTER_NAME}}/g' |
          -e 's/[[CONFIGIRATION_WORKSPACE_NAME]]/${{env.CONFIGIRATION_WORKSPACE_NAME}}/g' |
          -e 's/[[SCHEDULES_HIBERNATE_AT]]/${{env.SCHEDULES_HIBERNATE_AT}}/g' |
          -e 's/[[SCHEDULES_WAKE_AT]]/${{env.SCHEDULES_WAKE_AT}}/g' |
          .github/astro_deployment_template.yaml

      - name: Final astro deployment template YAML
        run: |
          echo .github/astro_deployment_template.yaml

      
          pytest: true
