#
name: Create astro feature deployment
run-name: Create astro feature deployment
on:
  workflow_dispatch:

jobs:
  check_conditions:
    name: Check conditions
    runs-on: ubuntu-latest
    env:
      REPO_NAME: 'ci-cd' # 'astro-dev-insights-core-ae'
    outputs:
      should-run-next: ${{ steps.condition-check.outputs.run-next }}
    steps:
      - name: Set CURRENT_REPO_NAME
        run: echo "CURRENT_REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Common information
        run: |
          echo "Create astro deployment for the PR ${{ github.event.pull_request.html_url }}"
          echo "Current repo name: ${{env.CURRENT_REPO_NAME}}"
          echo "Core repo name: ${{env.REPO_NAME}}"
          echo "The source branch: ${{github.ref}}"
          echo "github.action_ref: ${{github.action_ref}}"
          echo "github.action_repository: ${{github.action_repository}}"
          echo "github.base_ref: ${{github.base_ref}}"
          echo "github.head_ref: ${{github.head_ref}}"
          echo "github.ref_name: ${{github.ref_name}}"
          echo "github.ref_type: ${{github.ref_type}}"
          
          echo "github.event.head_commit.message: ${{github.event.head_commit.message}}"


          


          

      - name: Conditions are not met
        run: |
          echo "The deploment can be created only from the non-dev and non-main brunch and can be invocated only from the repo ${{env.REPO_NAME}}"
          echo "Current repo name ${{env.CURRENT_REPO_NAME}} or branch ${{github.ref}} does not satisfy the condition"
        if: env.CURRENT_REPO_NAME != env.REPO_NAME || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'

      - id: condition-check
        name: Conditions are met
        run: |
          echo "run-next=true" >> "$GITHUB_OUTPUT"
        if: env.CURRENT_REPO_NAME == env.REPO_NAME && github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev'

  create_deployment:
    name: Create astro deployment for the PR
    needs: check_conditions
    if: needs.check_conditions.outputs.should-run-next == 'true'
    runs-on: ubuntu-latest
    env:
      DATABRIKS_CONN: ${{ secrets.ASTRO_DATABRIKS_CONN }}
      # Name of deployment: Please note that the team name will be calculated based on the value of this deployment's name.
      CONFIGIRATION_NAME: "insights-${{github.ref_name}}-core-ae-dev"
      CONFIGIRATION_DESCRIPTION: "Auto create from the branch ${{github.ref_name}}"
      CONFIGIRATION_CLUSTER_NAME: "dedicated-cluster"
      CONFIGIRATION_WORKSPACE_NAME: "dev-workspace-insights"
      # The values for the hibernate scheduler are only provided as an example, so by default, the hibernate scheduler is disabled and can be activated manually.
      SCHEDULES_HIBERNATE_AT: "0 18 * * 1-5"
      SCHEDULES_WAKE_AT: "0 9 * * 1-5"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace Parameters in YAML
        run: envsubst < .github/astro_deployment_template.yaml > .github/processed_astro_feature_deployment_template.yaml

      - name: Final astro deployment template YAML
        run: |
          cat .github/processed_astro_feature_deployment_template.yaml

    
