name: Create astro feature deployment
on:
  workflow_dispatch:

jobs:
  check_conditions:
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      should-run-next: ${{ steps.condition_check.outputs.run-next }}
    steps:
      - id: condition_check  # Ensure the step ID matches what is referenced in outputs.
        name: Validate deployment conditions
        run: |
          echo "run-next=true" >> $GITHUB_ENV  # Correct the command to set env variable
        shell: bash

  create_deployment:
    name: Create astro deployment for the PR
    needs: check_conditions
    if: needs.check_conditions.outputs.should-run-next == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: ECHO
        run: echo "Run condition was met, proceeding with deployment."
