# Astronomer feature deployment GitHub action that create the Astronomer Deployment
# based on the Astronomer deployment template file .github/astro_feature_deployment_template.yaml

name: Create astro feature deployment
run-name: Create astro feature deployment
on:
  workflow_dispatch:

jobs:
  check_conditions:
    name: Check conditions
    runs-on: ubuntu-latest
    environment: dev
    outputs:
      should-run-next: ${{ steps.condition-check.outputs.run-next }}
    steps:
      - id: condition-check
        name: Conditions are met
        run: |
          echo "run-next=true" >> "$GITHUB_OUTPUT"

  create_deployment:
    name: Create astro deployment for the PR
    needs: check_conditions
    if: needs.check_conditions.outputs.should-run-next == 'true'
    runs-on: ubuntu-latest
    environment: dev    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
