# syntax 
#  https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps

#  https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context  

name: Automatically create PR for dependent projects
run-name: The ${{ github.event.pull_request.html_url }} 
on:
  pull_request:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
    types: closed # Trigger when a PR is closed
    #branches:
    #  - master
    #paths-ignore:
    #  - 'dags/**'
      
jobs:
  merge_pr:
    name: Create the PR for the dependent projects 
    runs-on: ubuntu-latest          
    env:
      #GITHUB_TOKEN: ${{ secrets.REPO_TOKEN_PR }}
      PR: ${{ github.event.pull_request.html_url }}
      SOURCE: ${{ github.event.pull_request.head.ref }}
      TARGET: ${{ github.event.pull_request.base.ref }}
    steps:      
      - id: check_condition
        run: |
            echo "condition_met=true" >> $GITHUB_ENV
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

      - name: Common information  
        run: |
          echo "The PR is $PR"
          echo "The PR source is $SOURCE"
          echo "The PR target is $TARGET"        

      - name: Checkout code
        if: env.condition_met == 'true'
        uses: actions/checkout@v4
      
      - name: Push Changes and Create PR to Repo2
        if: env.condition_met == 'true'
        uses: ahmadnassri/action-template-repository-sync@v2
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          config: .github/merge_to_main_conf.yml
          dry-run: false
