# syntax 
#  https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps

#  https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context  

name: Automatically create PR for dependent projects
run-name: The ${{github.ref}}
on:
  pull_request_target:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
    types: closed
    branches:
      - master
    #paths-ignore:
    #  - 'dags/**'
      
jobs:
  merge_pr:
    name: Create the PR for the dependent projects 
    runs-on: ubuntu-latest          
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR: ${{ github.event.pull_request.html_url }}
      SOURCE: ${{ github.event.pull_request.head.ref }}
      TARGET: ${{ github.event.pull_request.base.ref }}
    steps:      
      - name: Common information  
        run: |
          echo "The PR is $PR"
          echo "The PR source is $SOURCE"
          echo "The PR target is $TARGET"
                  
      - name: Checkout code
        if: github.event.pull_request.merged == true &&  github.event.pull_request.base.ref== 'main' # && github.event.pull_request.head.ref == 'dev'    
        uses: actions/checkout@v4
      - name: Setup Git config
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your GitHub Username"
      
      - name: Push Changes and Create PR to Repo2
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "dev" 
          destination_repository: "https://github.com/SavitskayaYlia/ci-cd-template.git" 
          github_token: ${{ secrets.REPO_TOKEN_PR }}
