name: Automatically create PR for dependent projects
run-name: The ${{github.ref}}
on:
  pull_request_target:
    types: closed # Trigger when a PR is closed
      
jobs:
  merge_pr:
    name: Create the PR for the dependent projects 
    runs-on: ubuntu-latest          
    env:
      GITHUB_TOKEN: ${{ secrets.REPO_TOKEN_PR }}
      PR: ${{ github.event.pull_request.html_url }}
      SOURCE: ${{ github.event.pull_request.head.ref }}
      TARGET: ${{ github.event.pull_request.base.ref }}
    steps:      
      - id: check_condition
        run: echo "condition_met=true" >> $GITHUB_ENV
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'

      - name: Common information  
        run: |
          echo "The PR is $PR"
          echo "The PR source is $SOURCE"
          echo "The PR target is $TARGET"
        if: env.condition_met == 'true' # Ensures that this step will run only if the condition from previous step is met

      - name: Checkout code
        if: env.condition_met == 'true'
        uses: actions/checkout@v4
      
      - name: Push Changes and Create PR to Repo2
        if: env.condition_met == 'true'
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "dev" 
          destination_repository: "https://github.com/SavitskayaYlia/ci-cd-template.git"
