# syntax 
#  https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps

#  https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context  

name: Create the PR for the dependent projects
run-name: The {{github.ref}}
on:
  pull_request:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
    types: closed
    #branches:
    #  - master
    #paths-ignore:
    #  - 'dags/**'
      
jobs:
  merge_pr:
    name: Create the PR for the dependent projects 
    if: github.event.pull_request.merged == true &&  github.event.pull_request.base.ref== 'master' # && github.event.pull_request.head.ref == 'dev'    
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR: ${{ github.event.pull_request.html_url }}
      SOURCE: ${{ github.event.pull_request.head.ref }}
      TARGET: ${{ github.event.pull_request.base.ref }}
    steps:
      - name: Common information  
        run: |
          echo "The PR is $PR"
          echo "The PR source is $SOURCE"
          echo "The PR target is $TARGET"
                  
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Merge Message
        run: echo "Changes from the dev branch have been merged into master!"
