name: secrets_and_var

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev 
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Use Environment Variables COMMON_SECRET
        run: echo "COMMON SECRET is ${{ secrets.COMMON_SECRET }}"
        
      - name: Use Environment Variables API_KEY
        run: echo "API Key is ${{ secrets.API_KEY }}"
