name: secrets_and_var

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev 
    outputs:
      deployment_id: ${{ steps.get_deployment_id.outputs.deployment_id }}
      deployment_existence: ${{ steps.check_deployment_existence.outputs.deployment_existence }}
      
    steps:
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - id: check_deployment_existence
        name: Check if deployment already exists
        run: |
          echo "deployment_existence=true" >> "$GITHUB_OUTPUT"
          echo "Deployment already exists"
          
      - name: Create deployment in astro false
        if: steps.check_deployment_existence.outputs.deployment_existence == 'false'
        run: echo " deployment_existence == false "
        
      - name: Create deployment in astro true
        if: steps.check_deployment_existence.outputs.deployment_existence == 'true'
        run: echo " deployment_existence == true "
