# syntax 
#  https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idsteps

#  https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context  

# As soon as any changes are merged into the main branch of a Git repository,
# a GitHub Action is triggered to create pull requests in S4 repositories.
name: Automatically create PR for S4 repositories
run-name: Auto propagation changes in main branch to S4 repositories
on:
  pull_request:
    types: closed
  workflow_dispatch: # for test purpose

jobs:
  create_pr:
    name: Create the PR for the S4 repositories
    runs-on: ubuntu-latest
    env:
      PR: ${{ github.event.pull_request.html_url }}
      TEMPLATE_REPO_NAME: 'astro-insights-template'
      condition_met: False

    steps:
      - name: Set CURRENT_REPO_NAME
        run: echo "CURRENT_REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

      - name: Check conditions
        run: |
          echo "Trigger this workflow when a PR is closed and meged to main branch of the repo ${{env.TEMPLATE_REPO_NAME}}"
          echo "condition_met=true" >> $GITHUB_ENV
        if: env.CURRENT_REPO_NAME == env.TEMPLATE_REPO_NAME && ((github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main') || github.event_name == 'workflow_dispatch')

      - name: Common information
        run: |
          echo "Auto propagation changes of PR ${{env.PR}}"
          echo "Current repo name is ${{env.CURRENT_REPO_NAME}}"
          echo "Template repo name is ${{env.TEMPLATE_REPO_NAME}}"
          echo "The PR source branch is ${{github.event.pull_request.head.ref}}"
          echo "The PR target branch is ${{github.event.pull_request.base.ref}}"
          echo "The PR is merged: ${{github.event.pull_request.merged}}"
          echo "Ð•he conditions for the sync are met: ${{env.condition_met}}"

      - name: Check repo name
        run: |
          echo "The 'automatically create PR for S4 repositories' action is not supported from the repo ${{env.CURRENT_REPO_NAME}}"
          echo "The action designed for the sunc of the ${{env.TEMPLATE_REPO_NAME}} repo and S4 repos and can be invocated only from the repo  ${{env.TEMPLATE_REPO_NAME}}"
          echo "The synchronization process will be omitted."
        if: env.CURRENT_REPO_NAME != env.TEMPLATE_REPO_NAME

        
      - name: Checkout code
        if: env.condition_met == 'true'
        uses: actions/checkout@v4
        
      - name: Push changes 
        if: env.condition_met == 'true'
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_TOKEN }}
          CONFIG_PATH: .github/sync_depended_projects_conf.yml
          PR_LABELS: |
            file-sync
            automatically-created
          #BRANCH_PREFIX: sync_${{github.run_id}} # add the prefix to pr branch
          PR_BODY: "Auto propagation changes of PR ${{env.PR}}"
          OVERWRITE_EXISTING_PR: true
          
